Use database to upload dumpling files to
molnard/Dumplings pull request #12
Opened 2022-12-06 09:48 UTC by Szpoti

**Work In Progress**

2022-12-12 11:40 UTC, molnard commented
Don't forget to remove the FTP script.

2022-12-14 10:28 UTC, molnard commented
Say when...

2022-12-14 12:38 UTC, Szpoti commented
> Say when...

I will :D Soon...
Final testing is happening

2023-02-09 12:25 UTC, molnard requested changes

2023-02-09 12:25 UTC, molnard commented on Dumplings/Displaying/Connect.cs
> +        public const string server = "178.238.222.15";
https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/csharp/language-compilers/store-custom-information-config-file

2023-02-09 12:25 UTC, molnard commented on Dumplings/Displaying/Connect.cs
> +                Console.WriteLine("Nem sikerült a kapcsolat" + err.Message);
Ángol!

2023-02-09 12:25 UTC, molnard commented on Dumplings/Displaying/Connect.cs
> +                return default(MySqlConnection);
return null?

2023-02-09 12:25 UTC, molnard commented on Dumplings/Displaying/Connect.cs
> +                return new MySqlConnection(conn);
Disposable?

2023-02-09 12:25 UTC, molnard commented on Dumplings/Constants.cs
> +        public static uint256 FirstWW1CoinJoinAfterNoCoordAddress = uint256.Parse("3e044598c2554f8b4479644aa3fc730d5d72ea5d2c5a3c002538268a2ea2f0fe");
Add a comment about what this is.

2023-02-09 12:25 UTC, molnard commented on Dumplings/Displaying/Connect.cs
> +        public const string server = "178.238.222.15";
Or you can add as argument in CLI as a connection string. Examples here https://www.connectionstrings.com/mysql/

2023-02-09 12:25 UTC, molnard commented on Dumplings.Cli/RunAndSendDumplings.sh
Add more comments on what this file does, how often, etc.

2023-02-09 12:25 UTC, molnard commented on Dumplings.Cli/RunAndSendDumplings.sh
>  echo "Syncronizing blockchain"
This is false.

![WishYouGIF](https://user-images.githubusercontent.com/9844978/217798151-90e4b9aa-a4b9-4c2d-8644-8399637c422c.gif)

2023-02-09 12:25 UTC, molnard commented on Dumplings/Stats/Statista.cs
> +                    MySqlCommand cmd = new MySqlCommand(sql, conn);
Disposable?

2023-02-09 12:28 UTC, molnard requested changes

2023-02-09 12:28 UTC, molnard commented on Dumplings.Cli/GetAndSendWWCoordStats.sh
> +# Send files from OUTFOLDER to email address
Talk with Kristaps to open a folder for Balint and set outfolder according to that.

2023-02-13 10:18 UTC, molnard commented
Ready to merge?

2023-02-13 10:20 UTC, Szpoti commented
I resolve the comments and after that, yes

2023-02-13 11:31 UTC, Szpoti commented
Ready

2023-02-14 10:39 UTC, molnard approved these changes
ACK

2023-02-14 10:39 UTC, merged